from django.db import transaction
from django.core.exceptions import ValidationError

from .models import Mission, UserMission
from .reward_service import (
    RewardService,
    BadgeRewardService,
)


class MissionService:

    @staticmethod
    @transaction.atomic
    def start_mission(user, mission):
        """
        Start a mission for a user.

        If the mission is already assigned to the user,
        the existing UserMission will be returned.
        """

        if not mission.is_active:
            raise ValidationError(
                "این ماموریت فعال نیست."
            )

        user_mission, created = UserMission.objects.get_or_create(
            user=user,
            mission=mission,
            defaults={
                "progress": 0,
                "status": "IN_PROGRESS",
            },
        )

        return user_mission, created

    @staticmethod
    @transaction.atomic
    def update_progress(user, mission, progress):
        """
        Update mission progress.

        Progress must be between 0 and 100.
        """

        if not mission.is_active:
            raise ValidationError(
                "این ماموریت فعال نیست."
            )

        if not 0 <= progress <= 100:
            raise ValidationError(
                "درصد پیشرفت باید بین 0 تا 100 باشد."
            )

        user_mission, created = UserMission.objects.get_or_create(
            user=user,
            mission=mission,
            defaults={
                "progress": 0,
                "status": "PENDING",
            },
        )

        # Completed missions must not move backwards.
        if user_mission.status == "COMPLETED":
            return user_mission, None

        user_mission.progress = progress

        if progress == 0:
            user_mission.status = "PENDING"

        elif progress < 100:
            user_mission.status = "IN_PROGRESS"

        else:
            user_mission.status = "COMPLETED"

        user_mission.save(
            update_fields=[
                "progress",
                "status",
                "updated_at",
            ]
        )

        reward = None

        if user_mission.status == "COMPLETED":
            reward = MissionService._handle_completion(
                user_mission
            )

        return user_mission, reward

    @staticmethod
    @transaction.atomic
    def complete_mission(user, mission):
        """
        Complete a mission for a user.

        This operation is idempotent.

        Completing the same mission multiple times
        will not award points or badges again.

        Returns:
            user_mission, reward
        """

        if not mission.is_active:
            raise ValidationError(
                "این ماموریت فعال نیست."
            )

        user_mission, created = UserMission.objects.get_or_create(
            user=user,
            mission=mission,
            defaults={
                "progress": 100,
                "status": "COMPLETED",
            },
        )

        # Already completed.
        # DO NOT award points or badges again.
        if not created and user_mission.status == "COMPLETED":
            return user_mission, None

        user_mission.progress = 100
        user_mission.status = "COMPLETED"

        user_mission.save(
            update_fields=[
                "progress",
                "status",
                "updated_at",
            ]
        )

        reward = MissionService._handle_completion(
            user_mission
        )

        return user_mission, reward

    @staticmethod
    @transaction.atomic
    def _handle_completion(user_mission):
        """
        Handle all rewards generated by mission completion.

        Flow:

        Mission Completion
            ↓
        Points
            ↓
        Level
            ↓
        Automatic Badges
            ↓
        Reward Result
        """

        user = user_mission.user
        mission = user_mission.mission

        # -----------------------------------------
        # 1. Award points + calculate level
        # -----------------------------------------

        point_result = RewardService.award_points(
            user=user,
            points=mission.points,
        )

        # -----------------------------------------
        # 2. Check automatic badges
        # -----------------------------------------

        badges = BadgeRewardService.check_automatic_badges(
            user=user
        )

        # -----------------------------------------
        # 3. Return complete reward information
        # -----------------------------------------

        return {
            "points": point_result["points"],
            "level_up": point_result["level_up"],
            "badges": badges,
        }