# Generated by Django 4.2.26 on 2026-07-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobposition_user_level_user_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('جویای کار', 'جویای کار'), ('استخدام شده', 'استخدام شده')], default='جویای کار', max_length=20),
        ),
    ]
