# Generated by Django 5.2.16 on 2026-08-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mission_remove_user_job_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='ApplicationAnswer',
        ),
    ]
