# Generated by Django 5.2.16 on 2026-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('HR', 'HR'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
