# Generated by Django 5.2.16 on 2026-08-27 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_mission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('MISSIONS_COMPLETED', 'Missions Completed')], max_length=50)),
                ('value', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='accounts.badge')),
            ],
        ),
    ]
