# Generated by Django 5.2.16 on 2026-08-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'در انتظار بررسی'), ('HR_REVIEW', 'در حال بررسی توسط HR'), ('WAITING_FOR_USER', 'در انتظار پاسخ کاربر'), ('MANAGEMENT_REVIEW', 'در حال بررسی توسط مدیریت'), ('ACCEPTED', 'پذیرفته شده'), ('REJECTED', 'رد شده')], default='PENDING_REVIEW', max_length=30),
        ),
    ]
