# Generated by Django 5.2.16 on 2026-09-02 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_team_onboarding_onboardingchecklistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('points', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('CHALLENGE', 'Challenge'), ('COMPETITION', 'Competition')], default='CHALLENGE', max_length=20)),
                ('event_link', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='accounts.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registered_at'],
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user'), name='unique_challenge_participant')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('prize', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='accounts.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', 'id'],
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user'), name='unique_challenge_winner')],
            },
        ),
    ]
