# Generated by Django 5.2.16 on 2026-09-03 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_challenge_challengeparticipant_challengewinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In Person')], max_length=20)),
                ('structure', models.CharField(choices=[('SINGLE', 'Single Part'), ('MULTI', 'Multi Part')], default='SINGLE', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('instructor_name', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('sessions_count', models.PositiveIntegerField(default=1)),
                ('points', models.PositiveIntegerField(default=0)),
                ('event_link', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('content_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.trainingcourse')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='ENROLLED', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.trainingcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTrainingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='accounts.trainingsection')),
                ('user_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_sections', to='accounts.usertraining')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingsection',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_training_section_order'),
        ),
        migrations.AddConstraint(
            model_name='usertraining',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_training'),
        ),
        migrations.AddConstraint(
            model_name='usertrainingsection',
            constraint=models.UniqueConstraint(fields=('user_training', 'section'), name='unique_user_training_section'),
        ),
    ]
