# Generated by Django 5.2.16 on 2026-09-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_trainingcourse_trainingsection_usertraining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatic_missions', to='accounts.jobposition'),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='target_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
