# Generated by Django 5.2.16 on 2026-09-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_mission_job_position_mission_target_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='accounts.jobapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
