# Generated by Django 5.2.16 on 2026-09-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_applicationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='required_missions',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of completed missions required to earn this badge.', null=True),
        ),
        migrations.DeleteModel(
            name='BadgeRule',
        ),
    ]
